### ISSUE TITLE
can symmetry-kernel be used in Transpose convolution?

### ISSUE THREAD

**Issue by lkqnaruto** [Gayan225/Symmetry-Structured-Convolutional-Neural-Networks#1]
I wonder if symmetry-kernel can be used in Transpose convolution?

**Comment by Gayan225** [comment]
Yes, it is possible to use a symmetry kernel in a transposed convolution operation. However, the specifics of how to do so would depend on the specific architecture and implementation details of your CNN.

In general, using a symmetry kernel in a transposed convolution operation could potentially help to preserve certain symmetries or invariances in your data, which could be useful for certain types of tasks or datasets.
